// <auto-generated />
namespace KhotruyenM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addalltabletodb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addalltabletodb));
        
        string IMigrationMetadata.Id
        {
            get { return "202206151451378_Add all table to db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
